# 推送内容
cn.yang37.easy-push.enabled=ding,sms
# 推送钉钉的URL,eg: https://oapi.dingtalk.com
cn.yang37.easy-push.ding.base-url=https://oapi.dingtalk.com
#cn.yang37.easy-push.ding.base-url=http://127.0.0.1:9595
cn.yang37.easy-push.ding.access-key=xx
cn.yang37.easy-push.ding.secret=xx

